version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: token-scraper-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: token_scraper
    ports:
      - "5432:5432"
    volumes:
      - token_scraper_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  token_scraper_data:
  qdrant_data:
